#!/bin/sh
# n2n-edge.init, 2019-08-16 00:11

### BEGIN INIT INFO
# Provides:             edged
# Required-Start:       $local_fs $network $named $time $syslog
# Required-Stop:        $local_fs $network $named $time $syslog
# Default-Stop:         2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Start n2n edge client
### END INIT INFO

#
# Author:   peterstrong<petterstrong007@gmail.com>
# 
NAME="edge"
DAEMON="/usr/sbin/${NAME}"


PIDFILE="/var/run/edge.pid"
LOGFILE="/ar/log/n2n-${NAME}.log"
STAMP=$(date +%T)

# Get the host/domain name to identify local configfile
HOST=$(hostname)
FQDN=$(hostname -f)

# Init configfile variable to empty value
CONFIGDIR="/etc/n2n"

# Init configfile variable to empty value
CONFIGFILE=""

if [ -z HOSTNAME ]; then
	exit 1
else
	CONFIGFILE="${CONFIGDIR}/edge-${HOST}"
fi

if [ -f "${CONFIGFILE}" ]; then
	echo "Find config file: ${CONFIGFILE}"
	. ${CONFIGFILE}
else
	echo "ERROR: Missing config file ${CONFIGFILE}"
	exit 1
fi

# See if pid exists and get pid number
if [ -f "${PIDFILE}" ]; then
	CURPID=$(cat ${PIDFILE})
fi

# Quit if we can't find app
# test -f ${} || exit

# read n2n config dir
if [ -d "${CONFIGDIR}" ]; then
	cd ${CONFIGDIR}
fi

start() {
	# echo
	echo "${STAMP} start n2n /etc/rc.d/init.d/${NAME}" > ${LOGFILE}

	if [ -n ${CURPID} ]; then
		echo "A PID: ${CURPID} already exists for ${0}:"
		echo "To restart with current config settings, run '${0} stop' then '${0} start' ..."
	fi
}

stop() {
}


case "$1" in 
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	*)
		echo -e "Usage: $0 [start|stop|start|uninstall]"
esac